### ISSUE TITLE
invalid envelop exception with ppi

### ISSUE THREAD

**Issue by pascalzellner** [Rexios80/polar#1]
Congrat it works perfectly with H10 and ECG streaming. With OH1, PPG streaming works two (there is a delay of about a few seconds; it's normal), but with PPI streaming, we have an invalid envelop exception.

![image](https://user-images.githubusercontent.com/61833861/122885156-1b56b600-d33f-11eb-98d0-e9eeb3ba5eec.png)

when in consult the SDK documentation PPI streaming don't need polar sensor settings parameters :

startOhrPPIStreaming()
abstract Flowable<PolarOhrPPIData> polar.com.sdk.api.PolarBleApi.startOhrPPIStreaming	(	@NonNull final String 	identifier	)	

While PPG and ECG need PolarSensorSetting, perhaps the problem comes from lines 325 and 334 in polar.dart. It's almost a question because I'm really a dummy about platform_channel.

**Comment by Rexios80** [comment]
I bet I know what it is. I'm requesting sensor settings for PPI but if they don't exist that's probably what's causing the error.

**Comment by Rexios80** [comment]
It might still not work but I at least fixed the issue with trying to fetch settings for the PPI sensor

**Comment by Rexios80** [comment]
Run `flutter pub upgrade` and you should get the updated version of the plugin

**Comment by pascalzellner** [comment]
It works perfectly. I saw that you modified startOHRPPiStreaming code. Notes when the ppi sample blockerBit is true the polar OH1 firmware give a heart at 0 (in ppi sample & hr streaming), because the PPI calculation is supposed wrong. When blockerBit is false, you have the HR value in ppi sample & hr streaming. So we can only use ppi value on a rest examination, the firmware don't correct hr value with accelerometer info in ppi mode but only on single hr streaming mode. Many thanks to this work. Now we will can try OH1, H10, verity sense in ours APPs for research projects. So the only way to access RR values at work will be the H10.

**Comment by pascalzellner** [comment]
I close this issue
