### ISSUE TITLE
device_info_plus upgrade .... again

### ISSUE THREAD

**Issue by bardram** [Rexios80/polar#12]
The [device_info_plus](https://pub.dev/packages/device_info_plus) is now - again - upgraded to a version 8.0.0.

Could you upgrade to this?

Thanks for a very useful plugin.

**Comment by Rexios80** [comment]
😑

**Comment by Rexios80** [comment]
Done in `3.4.0`

**Comment by bardram** [comment]
Thanks for the quick update!
