### ISSUE TITLE
"An App is needed to use this device" issue

### ISSUE THREAD

**Issue by clockwork189** [Rexios80/polar#2]
Hello,
Thanks for developing and maintaining this plugin! It works great for most part however, we recently discovered an issue, mainly on newer Samsung Devices, where the device will be unable to connect to the Polar Devices and give an error saying "An app is needed to use this device". I have attached a screenshot below. Is there a way with the api to bypass this? Or force the device to connect to the polar device?

<img width="652" alt="Screen Shot 2021-12-22 at 12 22 34 PM" src="https://user-images.githubusercontent.com/949323/147131313-511bfd34-9dac-45d5-8ec1-f8a9bfc770d9.png">

Apologies if this is irrelevant to the library. Thanks again for your work on this plugin!

**Comment by Rexios80** [comment]
This plugin is just a wrapper for the native SDKs. 

If you have any questions about the API it's probably best to create an issue on the repo for them.

https://github.com/polarofficial/polar-ble-sdk
