### ISSUE TITLE
Update PolarBleSdk to SDK 5.3.0

### ISSUE THREAD

**Issue by LarsRefsgaard** [Rexios80/polar#20]
https://github.com/polarofficial/polar-ble-sdk/blame/fd1a0dcda47f09b2ec6fa2367ceb6af2e2241b31/sources/iOS/ios-communications/Sources/iOSCommunications/ble/api/BleDeviceListener.swift#L118

This line fails on SDK 5.2.0, due to a typing error. This error seems to be fixed or at least changed on SDK 5.3.0, hopefully fixed.

**Comment by Rexios80** [comment]
Blocked on https://github.com/polarofficial/polar-ble-sdk/issues/393
