### ISSUE TITLE
Polar Verity Sense - gyroscope frequency?

### ISSUE THREAD

**Issue by zemmyang** [Rexios80/polar#22]
(Device is a Verity Sense, testing on Android)

I added the following to the `streamWhenReady` function in the sample app:

```
    if (availabletypes.contains(PolarDataType.gyro)) {
      polar
          .startGyroStreaming(identifier)
          // .listen((e) => log('Gyroscope data: ${e.samples.map((e) => e.timeStamp)}: ${e.samples.map((e) => e.x)}'));
          .listen((e) => log('Gyroscope data: ${e.samples.length} samples'));
    }
```

I'm receiving 1 log entry per second, and the sample length varies between log entry - sometimes it's 130, sometimes it's 55, etc. As I understand, e.samples is a list of the sample data received, each with its own timestamp and xyz value. From the SDK documentation, the freq of the gyroscope is 52Hz. Am I supposed to concatenate the samples together to get the gyroscope data?

ps: Unrelated, why does HR have no timestamp?

**Comment by Rexios80** [comment]
This sounds like a question for the official repository

https://github.com/polarofficial/polar-ble-sdk

**Comment by zemmyang** [comment]
ok, i asked there. thanks

https://github.com/polarofficial/polar-ble-sdk/issues/439
