### ISSUE TITLE
Stream When Ready Not working

### ISSUE THREAD

**Issue by ddbhuva** [Rexios80/polar#25]
I have connected to the device, but it is not logging anything after making the connection to Polar. It is showing battery level..
<img width="425" alt="Screenshot 2024-04-19 at 11 38 42 AM" src="https://github.com/Rexios80/polar/assets/99238106/3e9c2de7-18e7-4ce6-9d01-de0492a7165d">
 

`import 'package:flutter/material.dart';
import 'package:polar/polar.dart';
import 'package:uuid/uuid.dart';

void main() {
  runApp(const MyApp());
}

/// Example app
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String identifier = '';
  List<PolarDeviceInfo> devices = [];

  final polar = Polar();
  final logs = [''];

  PolarExerciseEntry? exerciseEntry;
  bool searchOnlyPolar = true;
  List<PolarDeviceInfo> selectedDevices = [];

  @override
  void initState() {
    super.initState();

    polar.batteryLevel.listen((e) => log('Battery: ${e.level}'));
    polar.deviceConnecting.listen((_) => log('Connecting to Device...'));
    polar.deviceConnected.listen((_) => log('Device connected'));
    polar.deviceDisconnected.listen((_) => log('Device disconnected'));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Tracking Method'),
            actions: const [
              /*
            PopupMenuButton(
              itemBuilder: (context) => RecordingAction.values
                  .map((e) => PopupMenuItem(value: e, child: Text(e.name)))
                  .toList(),
              onSelected: handleRecordingAction,
              child: const IconButton(
                icon: Icon(Icons.fiber_manual_record),
                disabledColor: Colors.black,
                onPressed: null,
              ),
            ),
            
            IconButton(
              icon: const Icon(Icons.search),
              onPressed: () {
                log('Disconnecting from device: $identifier');
                polar.disconnectFromDevice(identifier);
              },
            ),
            
              IconButton(
                icon: const Icon(Icons.search),
                onPressed: () {
                  log('Searching...:');
                  _startSearching();
                },
              ),
              */
            ],
          ),
          body: _listWithDeviceLog()),
    );
  }

  void _startSearching() {
    polar.searchForDevice().listen((e) {
      setState(() {
        devices.add(e);
      });
    });
  }

  Widget _listWithDeviceLog() {
    return Column(
      children: [
        ElevatedButton(
          onPressed: () {
            log('Searching...:');
            _startSearching();
          },
          child: const Text('Search Polar Device'),
        ),
        /*
        Padding(
          padding: const EdgeInsets.all(15.0),
          child: PopupMenuButton(
            itemBuilder: (context) => RecordingAction.values
                .map((e) => PopupMenuItem(value: e, child: Text(e.name)))
                .toList(),
            onSelected: handleRecordingAction,
            child: const ElevatedButton(
              onPressed: null,
              child: Row(
                children: [
                  Text('More Options'),
                  IconButton(
                    icon: Icon(Icons.arrow_drop_down),
                    disabledColor: Colors.black,
                    onPressed: null,
                  )
                ],
              ),
            ),
          ),
        ),
        */
        Expanded(
          child: ListView.builder(
            itemCount: devices.length,
            itemBuilder: (context, index) {
              final device = devices[index];
              if (searchOnlyPolar && !device.name.contains("Polar"))
                return Container();
              return ListTile(
                onTap: () {
                  log('Connecting to device: $identifier');
                  if (!selectedDevices.contains(device)) {
                    setState(() {
                      selectedDevices.add(device);
                    });
                  }
                  identifier = device.deviceId;
                  _connectToDevice();

                  // Navigator.push(
                  //   context,
                  //   MaterialPageRoute(
                  //       builder: (context) => DeviceView(
                  //           device: device, polarBleSdk: polarBleSdk)),
                  // );

                  // setState(() {
                  //   if (selectedDevices.contains(device)) {
                  //     selectedDevices.remove(device);
                  //   } else {
                  //     selectedDevices.add(device);
                  //   }
                  // });
                },
                selected: selectedDevices.contains(device),
                title: Text(device.name.isNotEmpty ? device.name : 'unknown'),
                subtitle: Text(device.address),
                trailing: SizedBox(
                  height: 64,
                  width: 64,
                  child: Row(
                    children: [
                      Text("${device.rssi}"),
                      const SizedBox(
                        width: 8,
                      ),
                      Icon(
                        Icons.circle,
                        color: device.isConnectable == true
                            ? Colors.green
                            : Colors.red,
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),
        Expanded(
          child: ListView(
            padding: const EdgeInsets.all(10),
            shrinkWrap: true,
            children: logs.reversed.map(Text.new).toList(),
          ),
        ),
      ],
    );
  }

  Future<void> _connectToDevice() async {
    await polar.connectToDevice(identifier);
    streamWhenReady();
  }

  Future<void> getSettings() async {
    await polar.enableSdkMode(identifier);
    log('SDK Mode STATUS:');

    final settings =
        await polar.requestStreamSettings(identifier, PolarDataType.hr);

    log('Settings: ${settings.settings}');
  }

  void streamWhenReady() async {
    await polar.sdkFeatureReady.firstWhere(
      (e) =>
          e.identifier == identifier &&
          e.feature == PolarSdkFeature.onlineStreaming,
    );
    log('Sdk features');
    final availabletypes =
        await polar.getAvailableOnlineStreamDataTypes(identifier);

    getSettings();

    debugPrint('available types: $availabletypes');
    log('available types: ${availabletypes.toString()}');

    if (availabletypes.contains(PolarDataType.hr)) {
      polar
          .startHrStreaming(identifier)
          .listen((e) => log('Heart rate: ${e.samples.map((e) => e.hr)}'));
    } else {
      log('HR data Not Available');
    }
    if (availabletypes.contains(PolarDataType.ecg)) {
      polar
          .startEcgStreaming(identifier)
          .listen((e) => log('ECG data received'));
    }
    if (availabletypes.contains(PolarDataType.acc)) {
      polar
          .startAccStreaming(identifier)
          .listen((e) => log('ACC data received'));
    }

    polar
        .startHrStreaming(identifier)
        .listen((e) => log('BPM: ${e.samples.map((e) => e.hr)}'));
  }

  void log(String log) {
    // ignore: avoid_print
    print(log);
    setState(() {
      logs.add(log);
    });
  }

  Future<void> handleRecordingAction(RecordingAction action) async {
    switch (action) {
      case RecordingAction.start:
        log('Starting recording');
        await polar.startRecording(
          identifier,
          exerciseId: const Uuid().v4(),
          interval: RecordingInterval.interval_1s,
          sampleType: SampleType.rr,
        );
        log('Started recording');
        break;
      case RecordingAction.stop:
        log('Stopping recording');
        await polar.stopRecording(identifier);
        log('Stopped recording');
        break;
      case RecordingAction.status:
        log('Getting recording status');
        final status = await polar.requestRecordingStatus(identifier);
        log('Recording status: $status');
        break;
      case RecordingAction.list:
        log('Listing recordings');
        final entries = await polar.listExercises(identifier);
        log('Recordings: $entries');
        // H10 can only store one recording at a time
        exerciseEntry = entries.first;
        break;
      case RecordingAction.fetch:
        log('Fetching recording');
        if (exerciseEntry == null) {
          log('Exercises not yet listed');
          await handleRecordingAction(RecordingAction.list);
        }
        final entry = await polar.fetchExercise(identifier, exerciseEntry!);
        log('Fetched recording: $entry');
        break;
      case RecordingAction.remove:
        log('Removing recording');
        if (exerciseEntry == null) {
          log('No exercise to remove. Try calling list first.');
          return;
        }
        await polar.removeExercise(identifier, exerciseEntry!);
        log('Removed recording');
        break;
    }
  }
}

enum RecordingAction {
  start,
  stop,
  status,
  list,
  fetch,
  remove,
}
`

**Comment by Rexios80** [comment]
Does it work with the example app?

**Comment by Rexios80** [comment]
I'm closing this since there has been no response for 2 weeks. Feel free to reopen if you have more info.
