### ISSUE TITLE
Communication conflict with flutter_background_service library.

### ISSUE THREAD

**Issue by gkois** [Rexios80/polar#26]
I would like to initially thank you for your excellent library.

In a project I am involved in, we want to use your library together with the flutter_background_service library.
We noticed that when the flutter background service is started, polar connects but never responds when calling
```code
polar.sdkFeatureReady.firstWhere(...)
```

Attached bellow is a public repo with a sample project displaying the issue.

[https://github.com/gkois/flutter_polar_issue.git](https://github.com/gkois/flutter_polar_issue.git)

If you can provide any insight on what could be the problem, it would be of great help.

Thank you in advance.

**Comment by marthan94** [comment]
Hi! I faced the same issue! It would be perfect if we can find a solution! :)

**Comment by Rexios80** [comment]
What platform are you running on?

**Comment by gkois** [comment]
We are developing on Android 12.

**Comment by Rexios80** [comment]
I think the flutter_background_service isn't well supported so we've used the foreground service from flutter_local_notifications: https://github.com/MaikuB/flutter_local_notifications/blob/5375645b01c845998606b58a3d97b278c5b2cefa/flutter_local_notifications/example/lib/main.dart#L2415

We have had no issues running the polar plugin along side it.

**Comment by gkois** [comment]
Thanx for the recommendation. We will try flutter_local_notifications and I will come back with update if it works.

**Comment by Rexios80** [comment]
@gkois any luck?

**Comment by gkois** [comment]
@Rexios80 we managed to get it working on a demo app.
we are in the process of incorporating it to the main app.

thank you for your help.

**Comment by Rexios80** [comment]
What was the issue?
