### ISSUE TITLE
How to get timestamp while streaming HR.

### ISSUE THREAD

**Issue by pranav243** [Rexios80/polar#30]
if (availabletypes.contains(PolarDataType.hr)) {
      polar.startHrStreaming(identifier).listen((data) {      
        int hr = data.samples.first.hr;
     }
}
In ecg and ACC i can get the timestamp by doing data.samples.first.timeStamp. But the same attribute is not available for hr it seems. 
How do i access the timestamp sent with the hr?

**Comment by Rexios80** [comment]
See https://github.com/polarofficial/polar-ble-sdk/issues/329

I'm not sure they ever actually implemented it

**Comment by pranav243** [comment]
Why would that be though? Don't you need precise timestamps of when the data was recorded? As using the local time on my mobile device won't be accurate.

**Comment by Rexios80** [comment]
I'm not sure you'd have to ask the Polar team

**Comment by pranav243** [comment]
https://github.com/fsmeraldi/bleakheart/blob/main/bleakheart.py
In this the user is able to get the timeStamp with hr value. Which means the SDK has the provision i guess.
