### ISSUE TITLE
Update for SDK 5.7.0

### ISSUE THREAD

**Issue by chrisgblr** [Rexios80/polar#35]
[Polar Ble SDK v.5.7.0](https://github.com/polarofficial/polar-ble-sdk/releases/tag/5.7.0) is out. Would be great to update the flutter plugin to this version.

**Comment by Rexios80** [comment]
What are you hoping to achieve with this? Is there any benefit to updating that doesn't require extra work?

**Comment by Rexios80** [comment]
Closing this since it is not actionable. If there are any specific features you would like implemented from new SDK versions, please create more descriptive issues.

**Comment by chrisgblr** [comment]
While I’m not looking for any specific new features introduced in 5.7.0, there were some bug fixes in version 5.6.0 that could be valuable in this Flutter plugin as well.

**Comment by GabrielKoletsi** [comment]
v5.6.0 had some useful feature additions too. v5.7.0 allows for firmware updates. Neat features, might contribute myself (if I find time and if I'm allowed to)

**Comment by Rexios80** [comment]
Released in version 7.4.0. Please create specific feature issues for any other desired functionality.
