### ISSUE TITLE
compileDebugKotlin seems not up to date

### ISSUE THREAD

**Issue by XababaDalabama** [Rexios80/polar#37]
Hello,

Just add the depedencies to a new flutter project. It works on IOS, but I can't manage to launch debug on android. 

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':polar:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain`

The current state of this Flutter project : 
`[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.93.1)`

any clue on this issue ? 

Thanks

**Comment by Rexios80** [comment]
This is a common Flutter issue that is easily searchable. If after searching you come up empty handed come back with more details.

**Comment by Rexios80** [comment]
Although maybe this is fixable by updating the plugin instead of projects that depend on it. I'll look into it.

**Comment by Rexios80** [comment]
I had this issue in the example project. I was able to resolve it with the following:
1. Open the project in Android Studio and use the AGP Upgrade Assistant to upgrade Gradle to version 8.6.1
2. Add the following to `android/build.gradle`:

```groovy
import org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension

subprojects {
    afterEvaluate {
        def kotlinExt = extensions.findByType(KotlinProjectExtension)
        if (kotlinExt != null) {
            kotlinExt.jvmToolchain(21)
        }
    }
}
```
